localhost ansible_connection=local

[internal]
latest ansible_ssh_host=10.10.10.24 ansible_ssh_private_key_file=~/.ssh/id_rsa
# demo   ansible_ssh_host=10.10.10.24 ansible_ssh_private_key_file=~/.ssh/id_rsa

# [external]
# live   ansible_ssh_host=10.10.10.24 ansible_ssh_private_key_file=~/.ssh/id_rsa
